apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
    type: NodePort
    app: nginxpod
  ports:  
   - protocol: TCP
     port: 80
     nodePort: 31010
     targetPort: nginxport
  
